# Defines services and containers for local development and testing
version: "3.9"
services:
  db:
    image: postgres:16
    container_name: CIMS_DB
    environment:
      FOO: BAR
    env_file:
      - .env
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
